/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ProxiedXMigrateToken__factory } from "./ProxiedXMigrateToken__factory";
export { XMigrateToken__factory } from "./XMigrateToken__factory";
