/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CrabCoin__factory } from "./CrabCoin__factory";
export { ProxiedCrabCoin__factory } from "./ProxiedCrabCoin__factory";
