/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Gin1689Coin } from "./Gin1689Coin";
export type { ProxiedGin1689Coin } from "./ProxiedGin1689Coin";
