/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mep1002NamingTokenMockSol from "./MEP1002NamingTokenMock.sol";
export type { mep1002NamingTokenMockSol };
import type * as mep1002TokenMockSol from "./MEP1002TokenMock.sol";
export type { mep1002TokenMockSol };
import type * as mep1004TokenMockSol from "./MEP1004TokenMock.sol";
export type { mep1004TokenMockSol };
import type * as lpwanMockSol from "./lpwanMock.sol";
export type { lpwanMockSol };
export type { ERC721Mock } from "./ERC721Mock";
