/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC6551Registry__factory } from "./ERC6551Registry__factory";
export { ProxiedERC6551Registry__factory } from "./ProxiedERC6551Registry__factory";
