/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ProxiedXMXCToken__factory } from "./ProxiedXMXCToken__factory";
export { XMXCToken__factory } from "./XMXCToken__factory";
