/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MaxisCoin__factory } from "./MaxisCoin__factory";
export { ProxiedMaxisCoin__factory } from "./ProxiedMaxisCoin__factory";
