/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EthMxcPriceAggregator__factory } from "./EthMxcPriceAggregator__factory";
export { ProxiedEthMxcPriceAggregator__factory } from "./ProxiedEthMxcPriceAggregator__factory";
