/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  TreasuryApproveToken,
  TreasuryApproveTokenInterface,
} from "../../../contracts/MEP2542.sol/TreasuryApproveToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "spender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "approveToken",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class TreasuryApproveToken__factory {
  static readonly abi = _abi;
  static createInterface(): TreasuryApproveTokenInterface {
    return new utils.Interface(_abi) as TreasuryApproveTokenInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TreasuryApproveToken {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as TreasuryApproveToken;
  }
}
