/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as utils from "./utils";
export type { utils };
export type { SSTORE2 } from "./SSTORE2";
export type { SSTORE2Map } from "./SSTORE2Map";
